### PR TITLE
Re- adding showdesktop.

### PR DESCRIPTION
**Pull request by Jacob-Vlijm**
In the python version of hotcorners, a showdesktop script was included. Later, the script was added to a shortcut. It got lost when we moved hotcorners to vala. Re- adding it now as part of budgie-desktop-environment.

### CODE REVIEW

**Comment by fossfreedom** [comment]
The only thing really missing is updating the gsettings key for users upgrading from 18.04 to 18.10.

**Comment by Jacob-Vlijm** [comment]
Can we add a self-killing/one-time autostart -edit from /etc/xdg/autostart?

**Comment by fossfreedom** [comment]
The scripts that always runs on login is the the two in etc/profile.d ... suggest we need a run once section that updates the key 

... if the key exists...
... if the key holds the old value

**Comment by Jacob-Vlijm** [comment]
Wait, @fossfreedom isn't it simpler to change budgie_desktop.sh to check for 18.10 final:
`if [ -f ~/.config/budgie-desktop/firstrun_18.10 ]`
(or `keycontrol_18.10`)

**Comment by Jacob-Vlijm** [comment]
Oh, wait, we'd still need to check if the key exists, right? Back to python.

**Comment by fossfreedom** [comment]
Correct. So if the user has already deleted the keybinding  then obviously don't need to do anything.

If the keybinding is still there but the user has defined it to something else we respect the user's decision and don't do anything

Only where the user has left the original keybinding in place to we update it with the new value

**Comment by fossfreedom** [comment]
I'll fix revert the caffeine addition manually

**Pull request merged**
